# docker-compose.yml
version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  backend:
    build: ./backend
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://mongo:27017
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend
